# Golang CircleCI 2.0 configuration file
version: 2
machine:
  environment:
    CC_TEST_REPORTER_ID: $CC_SECRET
dependencies:
  post:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
test:
  pre:
    - ./cc-test-reporter before-build
  post:
    - ./cc-test-reporter after-build --exit-code $EXIT_CODE
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
